// Per-account CODEX_HOME provisioning (ADR 0087 F4).
//
// This is the one place that answers "which Codex configuration is this turn
// running under", and the answer is never the user's own. Measured in the spike:
// with CODEX_HOME unset, a thread inherits the user's personal ~/.codex — eight
// of their MCP servers and their model (a Claude model through a custom
// provider) were loaded into a thread AWOG thought it had configured. That is
// the CLAUDE_CONFIG_DIR question of ADR 0070 with the OPPOSITE answer: skills,
// agents and commands are shared on purpose; a Codex runtime home is not.
//
// Layout: ~/.awog/codex/<accountId>/ — one home per AWOG account, which is also
// how Codex does multi-account (there is no account switch inside one home).
//
// Credentials are installed by running `codex login` with the secret on STDIN,
// never by writing auth.json ourselves: the file's shape is Codex's to own, and
// a hand-rolled one would silently rot on the next release.

import { execFile } from 'node:child_process'
import { createHash } from 'node:crypto'
import { chmod, mkdir, readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { awogHome, sanitizeChild } from '../../util/path.js'
import { resolveCodexBinary } from './binary.js'
import { dropCodexDaemon } from './app-server.js'
import { log } from '../../util/logger.js'

// Bumping this re-provisions every home on the next turn — use it when the
// generated config.toml changes in a way an existing home must pick up.
const PROVISION_VERSION = 1

const LOGIN_TIMEOUT_MS = 30_000

// What AWOG has already installed into a home, so a turn does not re-run
// `codex login` on every message. Holds a HASH of the credential, never the
// credential (invariant #1: the key does not leave the sidecar, and it has no
// business sitting in a second file on disk either).
interface ProvisionState {
  version: number
  credentialSha256: string
}

const STATE_FILE = '.awog-provision.json'

export function codexHomeFor(accountId: string): string {
  return join(awogHome(), 'codex', sanitizeChild(accountId))
}

function fingerprint(secret: string, mode: string): string {
  return createHash('sha256').update(`${mode}:${secret}`).digest('hex')
}

async function readState(home: string): Promise<ProvisionState | undefined> {
  try {
    const raw = await readFile(join(home, STATE_FILE), 'utf8')
    const parsed = JSON.parse(raw) as ProvisionState
    if (typeof parsed?.credentialSha256 !== 'string') return undefined
    return parsed
  } catch {
    return undefined
  }
}

// AWOG owns this file outright — the home is created by us and read by nobody
// else. Written on every provision so a changed template lands without needing
// the user to clear anything.
function configToml(): string {
  return [
    '# Generated by AWOG — do not edit.',
    '#',
    '# This CODEX_HOME belongs to one AWOG account. It is deliberately NOT the',
    "# user's own ~/.codex: a thread started under that home inherits their MCP",
    '# servers, model provider and skills (ADR 0087 F4).',
    '',
    'model_provider = "openai"',
    '',
    '# AWOG runs the approval flow in its own UI (the app-server routes approvals',
    '# to us as server requests), so Codex must not also try to reach a terminal.',
    'hide_agent_reasoning = false',
    '',
  ].join('\n')
}

async function runLogin(home: string, secret: string, flag: string): Promise<void> {
  const bin = resolveCodexBinary()
  await new Promise<void>((resolve, reject) => {
    const child = execFile(
      bin,
      ['login', flag],
      { env: { ...process.env, CODEX_HOME: home }, timeout: LOGIN_TIMEOUT_MS },
      (err, _stdout, stderr) => {
        // stderr is echoed into the error only: `codex login` prints a MASKED
        // key on success ("sk-test-***y-000"), and an unmasked one has never
        // been observed, but an error path is not the place to gamble on that.
        if (err) reject(new Error(`codex login failed: ${stderr.trim() || err.message}`))
        else resolve()
      },
    )
    child.stdin?.end(secret)
  })
}

/**
 * Make sure `~/.awog/codex/<accountId>` exists and holds THIS credential.
 *
 * Re-runs `codex login` only when the credential changed (ChatGPT access tokens
 * rotate on refresh, so this fires more often for a subscription account than
 * for an API key) or when the provisioning template moved. Returns the home path.
 */
export async function ensureCodexHome(args: {
  accountId: string
  secret: string
  /** ChatGPT subscription bearer (`cred.codex`) vs a plain API key. */
  kind: 'access-token' | 'api-key'
}): Promise<string> {
  const home = codexHomeFor(args.accountId)
  await mkdir(home, { recursive: true })
  // The home holds auth.json. 700 so it is no more readable than the rest of
  // ~/.awog (credentials.json is 600 for the same reason).
  await chmod(home, 0o700).catch(() => {
    /* best effort: a filesystem without POSIX modes must not fail the turn */
  })

  const want = fingerprint(args.secret, args.kind)
  const state = await readState(home)
  if (state?.credentialSha256 === want && state.version === PROVISION_VERSION) return home

  await writeFile(join(home, 'config.toml'), configToml(), 'utf8')
  await runLogin(home, args.secret, args.kind === 'api-key' ? '--with-api-key' : '--with-access-token')
  await writeFile(
    join(home, STATE_FILE),
    `${JSON.stringify({ version: PROVISION_VERSION, credentialSha256: want } satisfies ProvisionState, null, 2)}\n`,
    'utf8',
  )
  // A running daemon read auth.json at startup, so it is still holding the old
  // credential. Drop it; the next request spawns a fresh one.
  dropCodexDaemon(home)
  log.info('codex home provisioned', { accountId: args.accountId, kind: args.kind })
  return home
}
