packages:
  - apps/desktop/ui-next
  - apps/desktop/sidecar
  - apps/desktop/electron
  - apps/desktop/remote-pwa

allowBuilds:
  '@google/genai': true
  '@parcel/watcher': true
  cpu-features: true
  electron: true
  esbuild: false
  node-pty: true
  protobufjs: true
  ssh2: true
  unrs-resolver: true
  vue-demi: false
