packages:
  - apps/desktop/ui-next
  - apps/desktop/sidecar
  - apps/desktop/electron
  - apps/desktop/remote-pwa

allowBuilds:
  '@parcel/watcher': true
  esbuild: false
  vue-demi: false
  node-pty: true
  electron: true
