/* eslint-disable no-template-curly-in-string */
import type { Hook, SlashCommand } from '~/types'

export const INITIAL_HOOKS: Hook[] = [
  {
    id: 'prettier-ts',
    name: 'Prettier on TS files',
    description: 'Format TS/Vue/JSON ngay sau khi agent ghi.',
    event: 'artifact.after-write',
    matcher: { path: '**/*.{ts,vue,json}' },
    command: 'pnpm exec prettier --write {{event.payload.path}}',
    cwd: '${workspace}',
    timeoutMs: 10000,
    runMode: 'background',
    enabled: true,
    recentRuns: [
      { at: '2 phút trước', durationMs: 612, exitCode: 0 },
      { at: '8 phút trước', durationMs: 540, exitCode: 0 },
      { at: '15 phút trước', durationMs: 580, exitCode: 0 },
    ],
  },
  {
    id: 'block-gitignored',
    name: 'Block write to .gitignored paths',
    description: 'Ngăn agent ghi vào path nằm trong .gitignore (tránh leak secret).',
    event: 'artifact.before-write',
    matcher: {},
    command: 'node ./.awog/hooks/check-gitignore.mjs',
    cwd: '${workspace}',
    timeoutMs: 5000,
    runMode: 'blocking',
    enabled: true,
    recentRuns: [
      { at: '1 giờ trước', durationMs: 88, exitCode: 0 },
      {
        at: '3 giờ trước',
        durationMs: 92,
        exitCode: 1,
        stderr: 'Blocked: .env is in .gitignore',
      },
    ],
  },
  {
    id: 'slack-notify',
    name: 'Slack notification on completion',
    description: 'Ping #team-eng khi task hoàn thành hoặc fail.',
    event: 'task.after-complete',
    matcher: {},
    command:
      'curl -X POST -H "Content-type: application/json" --data \'{"text":"Task {{event.taskId}} {{event.payload.status}}"}\' $SLACK_WEBHOOK',
    cwd: '${workspace}',
    timeoutMs: 15000,
    runMode: 'background',
    enabled: false,
    env: { SLACK_WEBHOOK: '${secret:slack_webhook}' },
    recentRuns: [],
  },
  {
    id: 'auto-commit',
    name: 'Auto-commit after approval',
    description: 'Tạo commit Git sau khi phase được approve.',
    event: 'phase.after-approve',
    matcher: {},
    command: 'git add -A && git commit -m "AWOG: phase {{event.phaseId}} approved" --allow-empty',
    cwd: '${workspace}',
    timeoutMs: 8000,
    runMode: 'blocking',
    enabled: true,
    recentRuns: [
      { at: '15 phút trước', durationMs: 1240, exitCode: 0 },
      { at: '1 giờ trước', durationMs: 1180, exitCode: 0 },
    ],
  },
  {
    id: 'log-tool-calls',
    name: 'Audit tool calls',
    description: 'Ghi mọi tool call ra file audit để review sau.',
    event: 'tool.after-call',
    matcher: {},
    command: 'node ./.awog/hooks/log-tool.mjs',
    cwd: '${workspace}',
    timeoutMs: 3000,
    runMode: 'background',
    enabled: false,
    recentRuns: [],
  },
]

export const INITIAL_COMMANDS: SlashCommand[] = [
  {
    id: 'help',
    name: 'help',
    aliases: [],
    description: 'Hiển thị list command available.',
    type: 'prompt',
    args: [],
    body: 'Show me all available slash commands.',
    scope: 'global',
    system: true,
  },
  {
    id: 'clear',
    name: 'clear',
    aliases: [],
    description: 'Clear Discussion (giữ artifact).',
    type: 'prompt',
    args: [],
    body: '__system:clear_discussion__',
    scope: 'global',
    system: true,
  },
  {
    id: 'use',
    name: 'use',
    aliases: [],
    description: 'Đổi agent đang active.',
    type: 'agent-switch',
    args: [
      {
        name: 'agent',
        type: 'agent',
        required: true,
        description: 'Agent ID hoặc name',
      },
    ],
    body: '{{arg.agent}}',
    scope: 'global',
    system: true,
  },
  {
    id: 'approve',
    name: 'approve',
    aliases: [],
    description: 'Approve phase hiện tại.',
    type: 'prompt',
    args: [],
    body: '__system:approve_current_phase__',
    scope: 'global',
    system: true,
  },
  {
    id: 'review',
    name: 'review',
    aliases: ['r'],
    description: 'Yêu cầu agent review artifact gần nhất.',
    type: 'prompt',
    args: [
      {
        name: 'focus',
        type: 'string',
        required: false,
        description: 'Khía cạnh tập trung (security, perf, …)',
        default: 'toàn bộ',
      },
    ],
    body: 'Hãy review {{context.lastArtifact.path}} với focus vào {{arg.focus}}. Liệt kê bug, security issue, suggestion. Format: list bullet, mỗi item có severity + file:line.',
    scope: 'global',
  },
  {
    id: 'explain',
    name: 'explain',
    aliases: ['e'],
    description: 'Giải thích đoạn code đã chọn.',
    type: 'prompt',
    args: [
      {
        name: 'code',
        type: 'string',
        required: false,
        description: 'Code snippet (nếu không có, dùng selected text)',
      },
    ],
    body: 'Giải thích đoạn code sau, từ high-level intent đến chi tiết line-by-line. Nêu rõ side effect và edge case.\n\n```\n{{arg.code | default(context.selectedText)}}\n```',
    scope: 'global',
  },
  {
    id: 'run-tests',
    name: 'run-tests',
    aliases: [],
    description: 'Chạy test suite của project.',
    type: 'shell',
    args: [],
    body: 'pnpm test',
    scope: 'project:prj1',
    timeoutMs: 120000,
  },
  {
    id: 'git-status',
    name: 'git-status',
    aliases: ['gs'],
    description: 'Xem git status của workspace.',
    type: 'shell',
    args: [],
    body: 'git status --short',
    scope: 'global',
    timeoutMs: 5000,
  },
  {
    id: 'quick-fix',
    name: 'quick-fix',
    aliases: ['qf'],
    description: 'Trigger workflow quick-bug-fix.',
    type: 'workflow',
    args: [
      {
        name: 'issue',
        type: 'string',
        required: true,
        description: 'Mô tả bug',
      },
    ],
    body: 'wf2',
    scope: 'global',
  },
]
