import type { Hook } from '~/types'

export const INITIAL_HOOKS: Hook[] = [
  {
    id: 'prettier-ts',
    name: 'Prettier on TS files',
    description: 'Format TS/Vue/JSON ngay sau khi agent ghi.',
    event: 'artifact.after-write',
    matcher: { path: '**/*.{ts,vue,json}' },
    command: 'pnpm exec prettier --write {{event.payload.path}}',
    cwd: '${workspace}',
    timeoutMs: 10000,
    runMode: 'background',
    enabled: true,
    recentRuns: [
      { at: '2 phút trước', durationMs: 612, exitCode: 0 },
      { at: '8 phút trước', durationMs: 540, exitCode: 0 },
      { at: '15 phút trước', durationMs: 580, exitCode: 0 },
    ],
  },
  {
    id: 'block-gitignored',
    name: 'Block write to .gitignored paths',
    description: 'Ngăn agent ghi vào path nằm trong .gitignore (tránh leak secret).',
    event: 'artifact.before-write',
    matcher: {},
    command: 'node ./.awog/hooks/check-gitignore.mjs',
    cwd: '${workspace}',
    timeoutMs: 5000,
    runMode: 'blocking',
    enabled: true,
    recentRuns: [
      { at: '1 giờ trước', durationMs: 88, exitCode: 0 },
      {
        at: '3 giờ trước',
        durationMs: 92,
        exitCode: 1,
        stderr: 'Blocked: .env is in .gitignore',
      },
    ],
  },
  {
    id: 'slack-notify',
    name: 'Slack notification on completion',
    description: 'Ping #team-eng khi task hoàn thành hoặc fail.',
    event: 'task.after-complete',
    matcher: {},
    command:
      'curl -X POST -H "Content-type: application/json" --data \'{"text":"Task {{event.taskId}} {{event.payload.status}}"}\' $SLACK_WEBHOOK',
    cwd: '${workspace}',
    timeoutMs: 15000,
    runMode: 'background',
    enabled: false,
    env: { SLACK_WEBHOOK: '${secret:slack_webhook}' },
    recentRuns: [],
  },
  {
    id: 'auto-commit',
    name: 'Auto-commit after approval',
    description: 'Tạo commit Git sau khi phase được approve.',
    event: 'phase.after-approve',
    matcher: {},
    command: 'git add -A && git commit -m "AWOG: phase {{event.phaseId}} approved" --allow-empty',
    cwd: '${workspace}',
    timeoutMs: 8000,
    runMode: 'blocking',
    enabled: true,
    recentRuns: [
      { at: '15 phút trước', durationMs: 1240, exitCode: 0 },
      { at: '1 giờ trước', durationMs: 1180, exitCode: 0 },
    ],
  },
  {
    id: 'log-tool-calls',
    name: 'Audit tool calls',
    description: 'Ghi mọi tool call ra file audit để review sau.',
    event: 'tool.after-call',
    matcher: {},
    command: 'node ./.awog/hooks/log-tool.mjs',
    cwd: '${workspace}',
    timeoutMs: 3000,
    runMode: 'background',
    enabled: false,
    recentRuns: [],
  },
]
