import { Box, Database, FileText, FolderGit2, Layers, MessageSquare } from 'lucide-vue-next'
import type { Component } from 'vue'
import type { Agent, Project, Skill, Task, Workflow } from '~/types'
import { makeLiveTrace, makeTrace, mockOutput } from './mock-output'

export interface ContextProviderDef {
  id: string
  label: string
  icon: Component
}

export const CONTEXT_PROVIDERS: ContextProviderDef[] = [
  { id: 'artifacts', label: 'Artifacts', icon: FileText },
  { id: 'gitnexus', label: 'GitNexus', icon: FolderGit2 },
  { id: 'filesystem', label: 'Filesystem', icon: Database },
  { id: 'notion', label: 'Notion', icon: Box },
  { id: 'jira', label: 'Jira', icon: Layers },
  { id: 'slack', label: 'Slack', icon: MessageSquare },
]

export const INITIAL_SKILLS: Skill[] = [
  {
    id: 'sk1',
    name: 'gather_requirements',
    category: 'Analysis',
    description:
      'Translate stakeholder input into structured requirements with acceptance criteria.',
    inputs: ['raw_input', 'stakeholder_notes'],
    outputs: ['requirement.md'],
    promptTemplate:
      'Given the following stakeholder input, produce a structured requirements document with user stories and acceptance criteria.\n\nInput: {raw_input}\n\nFollow this format:\n## Context\n## User Stories\n## Acceptance Criteria',
    tags: ['planning', 'requirements'],
  },
  {
    id: 'sk2',
    name: 'write_user_stories',
    category: 'Analysis',
    description: 'Generate user stories in standard format from requirements.',
    inputs: ['requirement.md'],
    outputs: ['user_stories.md'],
    promptTemplate:
      'Convert the requirements into user stories using the "As a... I want... So that..." format.',
    tags: ['planning'],
  },
  {
    id: 'sk3',
    name: 'design_architecture',
    category: 'Design',
    description: 'Produce system architecture diagrams and component breakdowns.',
    inputs: ['requirement.md', 'existing_codebase'],
    outputs: ['architecture.md', 'component_diagram.mmd'],
    promptTemplate: 'Design a system architecture that satisfies the requirements.',
    tags: ['design', 'architecture'],
  },
  {
    id: 'sk4',
    name: 'design_api',
    category: 'Design',
    description: 'Create OpenAPI specifications for the feature.',
    inputs: ['requirement.md', 'architecture.md'],
    outputs: ['api.yaml'],
    promptTemplate: 'Produce an OpenAPI 3.0 spec for the endpoints.',
    tags: ['design', 'api'],
  },
  {
    id: 'sk5',
    name: 'implement_feature',
    category: 'Development',
    description: 'Write production code that implements the spec.',
    inputs: ['architecture.md', 'api.yaml'],
    outputs: ['source_code.zip', 'patch.diff'],
    promptTemplate: 'Implement the feature.',
    tags: ['code', 'implementation'],
  },
  {
    id: 'sk6',
    name: 'refactor_code',
    category: 'Development',
    description: 'Restructure existing code without changing behavior.',
    inputs: ['source_files'],
    outputs: ['patch.diff'],
    promptTemplate: 'Refactor.',
    tags: ['code', 'refactor'],
  },
  {
    id: 'sk7',
    name: 'fix_bug',
    category: 'Development',
    description: 'Reproduce and fix a defect in existing code.',
    inputs: ['issue_description', 'source_files'],
    outputs: ['patch.diff'],
    promptTemplate: 'Reproduce and fix.',
    tags: ['code', 'bugfix'],
  },
  {
    id: 'sk8',
    name: 'review_code',
    category: 'Quality',
    description: 'Identify bugs, security issues, and style violations in a code change.',
    inputs: ['patch.diff'],
    outputs: ['review.md'],
    promptTemplate: 'Review the code change.',
    tags: ['quality', 'review'],
  },
  {
    id: 'sk9',
    name: 'security_audit',
    category: 'Quality',
    description: 'Audit a code change for security vulnerabilities.',
    inputs: ['patch.diff', 'context'],
    outputs: ['security_report.md'],
    promptTemplate: 'Perform a security audit.',
    tags: ['security'],
  },
  {
    id: 'sk10',
    name: 'write_tests',
    category: 'Quality',
    description: 'Design and write a comprehensive test suite.',
    inputs: ['source_code.zip', 'architecture.md'],
    outputs: ['tests/'],
    promptTemplate: 'Design unit, integration, and edge-case tests.',
    tags: ['quality', 'testing'],
  },
  {
    id: 'sk11',
    name: 'run_qa',
    category: 'Quality',
    description: 'Execute test plan and produce a QA report.',
    inputs: ['source_code.zip', 'tests/'],
    outputs: ['test-report.md'],
    promptTemplate: 'Execute the test plan.',
    tags: ['quality', 'testing'],
  },
  {
    id: 'sk12',
    name: 'regression_check',
    category: 'Quality',
    description: 'Verify a change does not break existing functionality.',
    inputs: ['patch.diff'],
    outputs: ['regression-report.md'],
    promptTemplate: 'Re-run the existing test suite.',
    tags: ['quality'],
  },
]

export const INITIAL_AGENTS: Agent[] = [
  {
    id: 'ag1',
    name: 'Business Analyst',
    role: 'BA',
    model: 'claude-opus-4-7',
    skillIds: ['sk1', 'sk2'],
    context: ['notion', 'jira'],
    systemPrompt: 'You are a Business Analyst.',
  },
  {
    id: 'ag2',
    name: 'Solution Architect',
    role: 'SA',
    model: 'claude-opus-4-7',
    skillIds: ['sk3', 'sk4'],
    context: ['artifacts', 'gitnexus'],
    systemPrompt: 'You are a Solution Architect.',
  },
  {
    id: 'ag3',
    name: 'Senior Developer',
    role: 'DEV',
    model: 'claude-sonnet-4-6',
    skillIds: ['sk5', 'sk6', 'sk7'],
    context: ['artifacts', 'gitnexus', 'filesystem'],
    systemPrompt: 'You are a Senior Developer.',
  },
  {
    id: 'ag4',
    name: 'Code Reviewer',
    role: 'REVIEW',
    model: 'codex-1',
    skillIds: ['sk8', 'sk9'],
    context: ['artifacts', 'gitnexus'],
    systemPrompt: 'You are a Code Reviewer.',
  },
  {
    id: 'ag5',
    name: 'QA Engineer',
    role: 'QA',
    model: 'claude-sonnet-4-6',
    skillIds: ['sk10', 'sk11', 'sk12'],
    context: ['artifacts'],
    systemPrompt: 'You are a QA Engineer.',
  },
  {
    id: 'ag6',
    name: 'DevOps Engineer',
    role: 'DevOps',
    model: 'claude-sonnet-4-6',
    skillIds: ['sk6'],
    context: ['gitnexus', 'filesystem'],
    systemPrompt: 'You are a DevOps Engineer.',
  },
  {
    id: 'ag7',
    name: 'Security Specialist',
    role: 'Security',
    model: 'claude-opus-4-7',
    skillIds: ['sk9'],
    context: ['artifacts', 'gitnexus'],
    systemPrompt: 'You are a Security Specialist.',
  },
]

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'prj1',
    name: 'loyalty-service',
    path: '~/code/acme/loyalty-service',
    description: 'Customer loyalty and rewards backend',
    gitRemote: 'git@github.com:acme/loyalty-service.git',
    gitBranch: 'feat/loyalty-expiration',
    language: 'Python',
    createdAt: '3 months ago',
    color: '#a3a3a3',
  },
  {
    id: 'prj2',
    name: 'payment-service',
    path: '~/code/acme/payment-service',
    description: 'Payment processing and billing',
    gitRemote: 'git@github.com:acme/payment-service.git',
    gitBranch: 'fix/retry-race',
    language: 'Go',
    createdAt: '6 months ago',
    color: '#a3a3a3',
  },
  {
    id: 'prj3',
    name: 'admin-dashboard',
    path: '~/code/acme/admin-dashboard',
    description: 'Internal admin tools and customer support UI',
    gitRemote: 'git@github.com:acme/admin-dashboard.git',
    gitBranch: 'develop',
    language: 'TypeScript',
    createdAt: '1 month ago',
    color: '#a3a3a3',
  },
  {
    id: 'prj4',
    name: 'auth-service',
    path: '~/code/acme/auth-service',
    description: 'Authentication and authorization',
    gitRemote: 'git@github.com:acme/auth-service.git',
    gitBranch: 'main',
    language: 'Go',
    createdAt: '1 year ago',
    color: '#a3a3a3',
  },
]

export const INITIAL_WORKFLOWS: Workflow[] = [
  {
    id: 'wf1',
    name: 'Backend Feature Pipeline',
    description: 'Full feature development from requirements to QA',
    nodes: [
      {
        id: 'n1',
        agentId: 'ag1',
        skillId: 'sk1',
        x: 80,
        y: 60,
        outputs: ['requirement.md'],
        approval: false,
      },
      {
        id: 'n2',
        agentId: 'ag2',
        skillId: 'sk3',
        x: 80,
        y: 220,
        outputs: ['architecture.md', 'api.yaml'],
        approval: true,
      },
      {
        id: 'n3',
        agentId: 'ag3',
        skillId: 'sk5',
        x: 80,
        y: 380,
        outputs: ['source_code.zip'],
        approval: false,
      },
      {
        id: 'n4',
        agentId: 'ag4',
        skillId: 'sk8',
        x: 380,
        y: 380,
        outputs: ['review.md'],
        approval: false,
      },
      {
        id: 'n5',
        agentId: 'ag5',
        skillId: 'sk11',
        x: 230,
        y: 540,
        outputs: ['test-report.md'],
        approval: false,
      },
    ],
    edges: [
      { from: 'n1', to: 'n2' },
      { from: 'n2', to: 'n3' },
      { from: 'n3', to: 'n4' },
      { from: 'n3', to: 'n5' },
      { from: 'n4', to: 'n5' },
    ],
  },
  {
    id: 'wf2',
    name: 'Quick Bug Fix',
    description: 'Fast-track pipeline for bug fixes',
    nodes: [
      {
        id: 'n1',
        agentId: 'ag3',
        skillId: 'sk7',
        x: 80,
        y: 60,
        outputs: ['patch.diff'],
        approval: false,
      },
      {
        id: 'n2',
        agentId: 'ag4',
        skillId: 'sk8',
        x: 80,
        y: 220,
        outputs: ['review.md'],
        approval: true,
      },
      {
        id: 'n3',
        agentId: 'ag5',
        skillId: 'sk12',
        x: 80,
        y: 380,
        outputs: ['regression-report.md'],
        approval: false,
      },
    ],
    edges: [
      { from: 'n1', to: 'n2' },
      { from: 'n2', to: 'n3' },
    ],
  },
]

export const INITIAL_TASKS: Task[] = [
  {
    id: 'tsk-001',
    title: 'Add loyalty point expiration policy',
    projectId: 'prj1',
    source: {
      type: 'github',
      repo: 'acme/loyalty-service',
      issueNumber: 247,
      url: 'https://github.com/acme/loyalty-service/issues/247',
    },
    description:
      'Implement a 12-month expiration policy for loyalty points with email notifications 30 days before expiration.',
    workflowId: 'wf1',
    status: 'running',
    currentNodeId: 'n3',
    waitingApproval: null,
    waitingConnection: null,
    createdAt: '2 hours ago',
    phases: {
      n1: {
        nodeId: 'n1',
        status: 'completed',
        skillName: 'gather_requirements',
        runs: [
          {
            version: 1,
            status: 'completed',
            output: mockOutput('gather_requirements'),
            trace: makeTrace('ag1', 'requirements'),
            messages: [],
            duration: '24s',
          },
        ],
      },
      n2: {
        nodeId: 'n2',
        status: 'completed',
        skillName: 'design_architecture',
        runs: [
          {
            version: 1,
            status: 'superseded',
            output: 'Architecture v1 (initial draft) — used a single scheduler.',
            trace: makeTrace('ag2', 'architecture'),
            messages: [
              {
                role: 'user',
                text: 'This design uses a single scheduler — what if it falls behind?',
                at: '1h ago',
              },
            ],
            duration: '38s',
          },
          {
            version: 2,
            status: 'completed',
            output: mockOutput('design_architecture'),
            trace: makeTrace('ag2', 'architecture'),
            messages: [
              {
                role: 'agent',
                text: 'Good point. Revised to use 8 partitioned workers sharded by hash(user_id) % 8.',
                at: '58 min ago',
              },
            ],
            duration: '42s',
            approvedBy: 'human',
            approvedAt: '55 min ago',
          },
        ],
      },
      n3: {
        nodeId: 'n3',
        status: 'running',
        skillName: 'implement_feature',
        runs: [
          {
            version: 1,
            status: 'running',
            output: '',
            trace: makeLiveTrace('ag3'),
            messages: [],
            duration: null,
          },
        ],
      },
      n4: { nodeId: 'n4', status: 'pending', skillName: 'review_code', runs: [] },
      n5: { nodeId: 'n5', status: 'pending', skillName: 'run_qa', runs: [] },
    },
  },
  {
    id: 'tsk-002',
    title: 'Fix race condition in payment retry handler',
    projectId: 'prj2',
    source: {
      type: 'github',
      repo: 'acme/payment-service',
      issueNumber: 891,
      url: 'https://github.com/acme/payment-service/issues/891',
    },
    description:
      'Intermittent duplicate charges when retry handler executes concurrently with webhook callback.',
    workflowId: 'wf2',
    status: 'waiting_approval',
    currentNodeId: 'n2',
    waitingApproval: 'n2',
    waitingConnection: null,
    createdAt: '45 min ago',
    phases: {
      n1: {
        nodeId: 'n1',
        status: 'completed',
        skillName: 'fix_bug',
        runs: [
          {
            version: 1,
            status: 'completed',
            output: mockOutput('fix_bug'),
            trace: makeTrace('ag3', 'fix'),
            messages: [],
            duration: '52s',
          },
        ],
      },
      n2: {
        nodeId: 'n2',
        status: 'waiting_approval',
        skillName: 'review_code',
        runs: [
          {
            version: 1,
            status: 'waiting_approval',
            output: mockOutput('review_code'),
            trace: makeTrace('ag4', 'review'),
            messages: [],
            duration: '31s',
          },
        ],
      },
      n3: { nodeId: 'n3', status: 'pending', skillName: 'regression_check', runs: [] },
    },
  },
  {
    id: 'tsk-003',
    title: 'Add CSV export to admin dashboard',
    projectId: 'prj3',
    source: { type: 'manual' },
    description:
      'Admin users should be able to export customer lists as CSV with filtering applied.',
    workflowId: 'wf1',
    status: 'queued',
    currentNodeId: null,
    waitingApproval: null,
    waitingConnection: null,
    createdAt: '3 min ago',
    phases: {
      n1: { nodeId: 'n1', status: 'pending', skillName: 'gather_requirements', runs: [] },
      n2: { nodeId: 'n2', status: 'pending', skillName: 'design_architecture', runs: [] },
      n3: { nodeId: 'n3', status: 'pending', skillName: 'implement_feature', runs: [] },
      n4: { nodeId: 'n4', status: 'pending', skillName: 'review_code', runs: [] },
      n5: { nodeId: 'n5', status: 'pending', skillName: 'run_qa', runs: [] },
    },
  },
  {
    id: 'tsk-004',
    title: 'Implement OAuth token rotation',
    projectId: 'prj4',
    source: { type: 'jira', key: 'AUTH-512' },
    description: 'Rotate access tokens every 24 hours with seamless refresh for mobile clients.',
    workflowId: 'wf1',
    status: 'completed',
    currentNodeId: null,
    waitingApproval: null,
    waitingConnection: null,
    createdAt: 'Yesterday',
    phases: {
      n1: {
        nodeId: 'n1',
        status: 'completed',
        skillName: 'gather_requirements',
        runs: [
          {
            version: 1,
            status: 'completed',
            output: '# OAuth Rotation Requirements\n\nRotate every 24h.',
            trace: makeTrace('ag1', 'requirements'),
            messages: [],
            duration: '18s',
          },
        ],
      },
      n2: {
        nodeId: 'n2',
        status: 'completed',
        skillName: 'design_architecture',
        runs: [
          {
            version: 1,
            status: 'completed',
            output: '# Architecture\n\nUse refresh token grant.',
            trace: makeTrace('ag2', 'architecture'),
            messages: [],
            duration: '32s',
          },
        ],
      },
      n3: {
        nodeId: 'n3',
        status: 'completed',
        skillName: 'implement_feature',
        runs: [
          {
            version: 1,
            status: 'completed',
            output: '// auth.go\nfunc RotateToken() {...}',
            trace: makeTrace('ag3', 'fix'),
            messages: [],
            duration: '64s',
          },
        ],
      },
      n4: {
        nodeId: 'n4',
        status: 'completed',
        skillName: 'review_code',
        runs: [
          {
            version: 1,
            status: 'completed',
            output: '# Review\n\nLGTM',
            trace: makeTrace('ag4', 'review'),
            messages: [],
            duration: '22s',
          },
        ],
      },
      n5: {
        nodeId: 'n5',
        status: 'completed',
        skillName: 'run_qa',
        runs: [
          {
            version: 1,
            status: 'completed',
            output: '# QA\n\nAll tests passing',
            trace: makeTrace('ag5', 'review'),
            messages: [],
            duration: '28s',
          },
        ],
      },
    },
  },
  {
    id: 'tsk-005',
    title: 'Add dark mode to admin dashboard',
    projectId: 'prj3',
    source: { type: 'manual' },
    description: 'Support system theme detection plus manual override.',
    workflowId: 'wf1',
    status: 'queued',
    currentNodeId: null,
    waitingApproval: null,
    waitingConnection: null,
    createdAt: '1 hour ago',
    phases: {
      n1: { nodeId: 'n1', status: 'pending', skillName: 'gather_requirements', runs: [] },
      n2: { nodeId: 'n2', status: 'pending', skillName: 'design_architecture', runs: [] },
      n3: { nodeId: 'n3', status: 'pending', skillName: 'implement_feature', runs: [] },
      n4: { nodeId: 'n4', status: 'pending', skillName: 'review_code', runs: [] },
      n5: { nodeId: 'n5', status: 'pending', skillName: 'run_qa', runs: [] },
    },
  },
]
